name: Flutter CI

on:
  push:
    branches:
      - Flutter-app
  pull_request:
    branches:
      - Flutter-app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # ✅ FIXED

      - name: Install Flutter Manually (ARM)
        run: |
          sudo apt update
          sudo apt install -y curl unzip xz-utils git libglu1-mesa
          curl -o flutter.tar.xz https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.29.1-stable.tar.xz
          tar -xf flutter.tar.xz
          echo "FLUTTER_HOME=$PWD/flutter" >> $GITHUB_ENV
          echo "$PWD/flutter/bin" >> $GITHUB_PATH
          flutter --version

          

      - name: Install Java
        uses: actions/setup-java@v3  # ✅ FIXED
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Gradle
        run: |
          sudo apt-get update
          sudo apt-get install -y gradle

      - name: Clean project
        run: cd flutter-project && flutter clean

      - name: Get dependencies
        run: cd flutter-project && flutter pub get

      - name: Ensure Gradle Wrapper Exists
        run: |
          cd flutter-project/android
          chmod +x ./gradlew || ./gradlew wrapper  # ✅ FIXED

      - name: Build APK
        run: cd flutter-project && flutter build apk

      - name: Upload APK
        uses: actions/upload-artifact@v3  # ✅ FIXED
        with:
          name: app-release-apk
          path: flutter-project/build/app/outputs/flutter-apk/app-release.apk
