name: Flutter CI/CD

on:
  push:
    branches:
      - Flutter-app
  pull_request:
    branches:
      - Flutter-app

jobs:
  build:
    runs-on: ubuntu-latest  # ✅ Runs on GitHub's x86_64-hosted runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.1'
          channel: 'stable'

      - name: Verify Flutter installation
        run: flutter --version

      - name: Clean project
        run: flutter clean

      - name: Get dependencies
        run: flutter pub get

      - name: Ensure Gradle Wrapper is executable
        run: chmod +x android/gradlew

      - name: Build APK
        run: flutter build apk

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
